// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/products/delete": {
    params: {};
  };
  "/webhooks/products/update": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/debug/env": {
    params: {};
  };
  "/api/auth": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/products": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/webhooks/products/delete" | "/webhooks/products/update" | "/auth/login" | "/debug/env" | "/api/auth" | "/auth/*" | "/app" | "/app/additional" | "/app/products";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.products.delete.jsx": {
    id: "routes/webhooks.products.delete";
    page: "/webhooks/products/delete";
  };
  "routes/webhooks.products.update.jsx": {
    id: "routes/webhooks.products.update";
    page: "/webhooks/products/update";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/debug.env.jsx": {
    id: "routes/debug.env";
    page: "/debug/env";
  };
  "routes/api.auth.jsx": {
    id: "routes/api.auth";
    page: "/api/auth";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/additional" | "/app/products";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.products.jsx": {
    id: "routes/app.products";
    page: "/app/products";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.products.delete": typeof import("./app/routes/webhooks.products.delete.jsx");
  "routes/webhooks.products.update": typeof import("./app/routes/webhooks.products.update.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/debug.env": typeof import("./app/routes/debug.env.jsx");
  "routes/api.auth": typeof import("./app/routes/api.auth.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.products": typeof import("./app/routes/app.products.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};